In [4]:
import requests 
import pandas as pd

In [2]:
API_KEY = "API KEY" 
BASE_URL = 'https://api.themoviedb.org/3/movie/'

In [5]:
#retrive list of 100 top rated films TMDB version
def get_top_rated():
    response_list=[]
    for i in range(1,26):
        response = requests.get(BASE_URL + 'top_rated?api_key=' + API_KEY + '&page='+str(i)).json()  
        response_list.append(response)
    return response_list

In [6]:
# define column names for our new dataframe
columns = ['Top rated film', 'Numbers of males', 'Number of females', 'Non-binary','Budget','Revenue','Vote average','Vote Count','Popularity','Genre','Release Date', 'Production Country', 'Production Company']
# create dataframe with film and gender
df = pd.DataFrame(columns=columns)
response_list = get_top_rated()
for response in response_list: 
    top_rated_films = response['results']
    for film in top_rated_films:
            film_top = requests.get(BASE_URL + str(film['id']) +'/credits?api_key='+ API_KEY).json()
            film_details = requests.get(BASE_URL + str(film['id']) +'?api_key='+ API_KEY).json()
            female = 0 
            male = 0
            non_binary = 0
            not_specified = 0
            for cast in film_top['cast'][:6]:
            
                if cast['gender'] == 1:
                    female+=1 
                elif cast['gender'] == 2:
                    male+=1 
                elif cast['gender'] == 3:
                    non_binary+=1 
                else:
                    not_specified += 1
            country_data = []
            for country in film_details['production_countries']:
                country_data.append(country['name']
                )
            company_data = []
            for company in film_details['production_companies']:
                company_data.append(company['name'])
            
            df.loc[len(df)]=[film['title'],male,female,non_binary,film_details['budget'],film_details['revenue'],film_details['vote_average'],film_details['vote_count'],film_details['popularity'],film_details['genres'][0]['name'],film_details['release_date'],','.join(country_data), ','.join(company_data)]

In [7]:
df

,Top rated film,Numbers of males,Number of females,Non-binary,Budget,Revenue,Vote average,Vote Count,Popularity,Genre,Release Date,Production Country,Production Company
0,Your Eyes Tell,5,1,0,0,0,8.8,205,13.006,Romance,2020-10-23,Japan,Dragonfly Entertainment
1,Dilwale Dulhania Le Jayenge,4,2,0,13200000,100000000,8.7,3378,32.877,Comedy,1995-10-20,India,Yash Raj Films
2,The Shawshank Redemption,6,0,0,25000000,28341469,8.7,20620,89.872,Drama,1994-09-23,United States of America,Castle Rock Entertainment
3,The Godfather,4,1,0,6000000,245066411,8.7,15392,86.333,Drama,1972-03-14,United States of America,"Paramount,Alfran Productions"
4,Gabriel's Inferno Part II,2,4,0,0,0,8.6,1376,13.963,Romance,2020-07-31,,PassionFlix
...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Le Samouraï,3,3,0,0,39481,7.9,709,15.331,Crime,1967-10-25,"France,Italy","TC Productions,Compagnie Industrielle et Comme..."
496,Descendants 3,3,3,0,15000000,0,7.9,1180,82.708,Family,2019-08-02,United States of America,Disney Channel
497,Joint Security Area,5,1,0,12500000,0,7.9,428,14.767,War,2000-09-09,South Korea,"CJ Entertainment,Intz.com,KTB Network,Myung Films"
498,A Short Film About Love,3,2,0,0,0,7.9,246,12.688,Drama,1988-01-01,Poland,Zespół Filmowy TOR
499,Isle of Dogs,6,0,0,62770198,64241499,7.9,3724,24.187,Adventure,2018-03-23,"Germany,United States of America","Studio Babelsberg,American Empirical Pictures,..."

In [9]:
df.to_csv('updated_500.csv', index=False)